name: Auto-Update Flatpak Git Hashes

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [update-manifest]
  workflow_dispatch:

jobs:
  update-hashes:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install ruamel.yaml requirements-parser aiohttp

      - name: Fetch Latest Hashes and Update Manifest
        env:
          NEW_APP_TAG: ${{ github.event.client_payload.tag }}
        run: |
         python3 .github/tools/update-manifest.py

     
      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A in.atipra.ColrPak.yml 
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            TAG_MSG=${NEW_APP_TAG:-"latest"}
            git commit -m "chore: Update manifest colr-pak $TAG_MSG"
            git push
          fi
